import {Easing, Interactive, interpolate, useCurrentFrame} from 'remotion';
import {Dot, GlassPanel, Pill, Reveal, SceneChrome, colors} from '../components/Background';

const TraceRow: React.FC<{label:string;detail:string;at:number}> = ({label,detail,at}) => {
  const frame=useCurrentFrame(); const done=interpolate(frame,[at,at+12],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  return <div style={{display:'grid',gridTemplateColumns:'38px 1fr',gap:16,padding:'18px 0',borderBottom:'1px solid rgba(255,255,255,0.08)',opacity:interpolate(frame,[at-10,at+8],[0.2,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><div style={{width:32,height:32,borderRadius:999,display:'flex',alignItems:'center',justifyContent:'center',backgroundColor:done>0.7?colors.mint:'rgba(255,255,255,0.08)',color:done>0.7?colors.ink:colors.muted,fontWeight:900,fontSize:20}}>{done>0.7?'✓':'·'}</div><div><div style={{fontSize:25,fontWeight:900}}>{label}</div><div style={{fontSize:20,color:colors.muted,marginTop:4}}>{detail}</div></div></div>;
};

export const AgentScene: React.FC = () => {
  const frame=useCurrentFrame();
  return <SceneChrome chapter="KARAR KATMANI" index={4}><div style={{position:'absolute',left:88,right:88,top:132}}><Reveal delay={3}><Pill tone="cyan">LANGCHAIN AGENT</Pill></Reveal><Interactive.Div name="Agent başlığı" style={{marginTop:20,fontSize:83,lineHeight:1,fontWeight:900,letterSpacing:-3.8,opacity:interpolate(frame,[8,28],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)}),translate:`0px ${interpolate(frame,[8,30],[36,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)})}px`}}>AI yalnızca yazmıyor. <span style={{color:colors.cyan}}>Karar veriyor.</span></Interactive.Div></div><div style={{position:'absolute',left:88,right:88,top:340,bottom:108,display:'grid',gridTemplateColumns:'0.92fr 1fr 1.08fr',gap:24}}><Reveal delay={32}><GlassPanel style={{height:'100%',padding:30}}><Pill tone="muted">INPUT.JSON</Pill><div style={{fontFamily:'Courier New, monospace',fontSize:24,lineHeight:1.65,marginTop:32,color:colors.muted}}><div>{'{'}</div><div>&nbsp;&nbsp;"sku": "MED-2048",</div><div>&nbsp;&nbsp;"name": "Steril Set",</div><div>&nbsp;&nbsp;"stock": 84,</div><div>&nbsp;&nbsp;"language": "tr",</div><div>&nbsp;&nbsp;"image_ok": true</div><div>{'}'}</div></div><Reveal delay={118}><div style={{marginTop:30,padding:'18px 20px',borderRadius:16,backgroundColor:'rgba(154,255,189,0.09)',color:colors.mint,fontSize:22,fontWeight:800}}>✓ Şema doğrulandı</div></Reveal></GlassPanel></Reveal><Reveal delay={52}><GlassPanel accent="cyan" style={{height:'100%',padding:30}}><div style={{fontSize:24,fontWeight:900,color:colors.cyan}}>DECISION TRACE</div><div style={{marginTop:16}}><TraceRow label="Sınıflandır" detail="Kategori: sarf malzeme" at={68}/><TraceRow label="Politika kontrolü" detail="Zorunlu alanlar mevcut" at={102}/><TraceRow label="İçerik üret" detail="SEO başlık + açıklama" at={136}/><TraceRow label="Güven puanı" detail="0.93 → otomatik taslak" at={170}/></div></GlassPanel></Reveal><Reveal delay={86}><GlassPanel accent="warm" style={{height:'100%',padding:30}}><Pill tone="warm">OUTPUT</Pill><div style={{fontSize:33,fontWeight:900,marginTop:26}}>Steril Prosedür Seti — Tek Kullanımlık</div><div style={{fontSize:22,color:colors.muted,lineHeight:1.45,marginTop:16}}>Klinik süreçlerde hijyen ve operasyon hızını destekleyen eksiksiz sarf seti.</div><Reveal delay={206}><div style={{marginTop:28,padding:'17px 19px',backgroundColor:'rgba(154,255,189,0.11)',borderRadius:16,color:colors.mint,fontSize:22,fontWeight:900}}>SHOPIFY TASLAĞI HAZIR · 0.93</div></Reveal></GlassPanel></Reveal></div></SceneChrome>;
};
