import {Easing, Interactive, interpolate, useCurrentFrame} from 'remotion';
import {Dot, GlassPanel, Pill, Reveal, SceneChrome, colors} from '../components/Background';

const ManualCard: React.FC<{label:string;detail:string;index:string;delay:number}> = ({label,detail,index,delay}) => (
  <Reveal delay={delay}><GlassPanel style={{minHeight:214,padding:28,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{fontSize:20,fontWeight:800,color:colors.muted,letterSpacing:2.4}}>ADIM {index}</div><Dot tone={index==='04'?'warm':'mint'}/></div><div><div style={{fontSize:35,fontWeight:900,letterSpacing:-1.2}}>{label}</div><div style={{fontSize:24,color:colors.muted,marginTop:9}}>{detail}</div></div></GlassPanel></Reveal>
);

export const ChallengeScene: React.FC = () => {
  const frame=useCurrentFrame();
  return <SceneChrome chapter="VAKA" index={2}><div style={{position:'absolute',left:88,right:88,top:145}}><Reveal delay={4}><Pill tone="warm">MEDİKAL E-TİCARET OPERASYONU</Pill></Reveal><Interactive.Div name="Vaka başlığı" style={{fontSize:90,lineHeight:1.02,letterSpacing:-4.1,fontWeight:900,marginTop:24,maxWidth:1450,opacity:interpolate(frame,[8,30],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)}),translate:`0px ${interpolate(frame,[8,30],[42,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)})}px`}}>Yeni ürün geldiğinde iş <span style={{color:colors.warm}}>dört masaya</span> dağılıyordu.</Interactive.Div><Reveal delay={38}><div style={{fontSize:38,color:colors.muted,marginTop:22}}>Her devir: bekleme, kopyala-yapıştır ve veri tutarsızlığı riski.</div></Reveal><div style={{display:'grid',gridTemplateColumns:'repeat(4, 1fr)',gap:22,marginTop:70,position:'relative'}}><ManualCard label="Tedarikçi formu" detail="Ürün verisi gelir" index="01" delay={54}/><ManualCard label="Excel kontrolü" detail="Alanlar elle eşleşir" index="02" delay={68}/><ManualCard label="İçerik üretimi" detail="Başlık ve SEO yazılır" index="03" delay={82}/><ManualCard label="Panel + onay" detail="Kayıt ve ekip bildirimi" index="04" delay={96}/>{[0,1,2].map((item)=><div key={item} style={{position:'absolute',top:101,left:`${24.4+item*25.2}%`,width:24,height:24,borderTop:`3px solid ${colors.warm}`,borderRight:`3px solid ${colors.warm}`,rotate:'45deg'}}/>)}</div><Reveal delay={130} style={{display:'flex',justifyContent:'center',marginTop:40}}><div style={{display:'flex',alignItems:'center',gap:18,fontSize:28,fontWeight:800,color:colors.warm,padding:'16px 26px',border:'1px solid rgba(255,187,141,0.35)',borderRadius:999,backgroundColor:'rgba(255,187,141,0.08)'}}><Dot tone="warm" size={12}/>Tek hata noktası: manuel devirler</div></Reveal></div></SceneChrome>;
};
