import {Easing, Interactive, interpolate, useCurrentFrame} from 'remotion';
import {Dot, GlassPanel, Pill, Reveal, SceneChrome, colors} from '../components/Background';
import type {ShowcaseProps} from '../types';

const Deliverable: React.FC<{label:string;detail:string;delay:number}> = ({label,detail,delay}) => <Reveal delay={delay}><div style={{display:'grid',gridTemplateColumns:'46px 1fr',gap:20,alignItems:'center',padding:'20px 0',borderBottom:'1px solid rgba(255,255,255,0.09)'}}><div style={{width:40,height:40,borderRadius:999,backgroundColor:colors.mint,color:colors.ink,display:'grid',placeItems:'center',fontWeight:900,fontSize:24}}>✓</div><div><div style={{fontSize:27,fontWeight:900}}>{label}</div><div style={{fontSize:20,color:colors.muted,marginTop:4}}>{detail}</div></div></div></Reveal>;

export const ProofScene: React.FC<ShowcaseProps> = ({candidateName,contactLine,portfolioUrl,projectName}) => {
  const frame=useCurrentFrame();
  return <SceneChrome chapter="SONUÇ" index={6}><div style={{position:'absolute',left:88,right:88,top:142,bottom:104,display:'grid',gridTemplateColumns:'1.06fr 0.94fr',gap:64,alignItems:'center'}}><div><Reveal delay={4}><Pill>UÇTAN UCA OTOMASYON</Pill></Reveal><Interactive.Div name="Final başlığı" style={{marginTop:24,fontSize:100,lineHeight:0.98,letterSpacing:-4.8,fontWeight:900,opacity:interpolate(frame,[10,32],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)}),translate:`0px ${interpolate(frame,[10,34],[42,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)})}px`}}>Uçtan uca.<span style={{display:'block',color:colors.mint}}>Çalışır durumda.</span></Interactive.Div><Reveal delay={48}><div style={{fontSize:38,lineHeight:1.35,color:colors.muted,marginTop:34}}>Mimari kararlar, hata yönetimi ve gözlemlenebilir çıktılar tek akışta bir araya geliyor.</div></Reveal><Reveal delay={88}><div style={{display:'flex',alignItems:'center',gap:16,marginTop:42}}><Dot tone="cyan" size={14}/><div style={{fontSize:31,fontWeight:900}}>{candidateName}</div><div style={{fontSize:27,color:colors.muted}}>· {contactLine}</div></div><div style={{fontSize:23,color:colors.cyan,marginTop:15,marginLeft:30}}>{portfolioUrl}</div></Reveal></div><Reveal delay={28}><GlassPanel accent="cyan" style={{padding:'34px 38px'}}><div style={{fontSize:37,fontWeight:900}}>{projectName}</div><div style={{marginTop:20}}><Deliverable label="n8n workflow JSON" detail="İçe aktarılabilir akış" delay={56}/><Deliverable label="LangChain / FastAPI servis" detail="Structured output endpoint" delay={72}/><Deliverable label="README + mimari" detail="Kurulum ve karar kayıtları" delay={88}/><Deliverable label="50 saniyelik demo" detail="Teknik akış ve sonuç özeti" delay={104}/></div></GlassPanel></Reveal></div></SceneChrome>;
};
