import {Easing, Interactive, interpolate, useCurrentFrame} from 'remotion';
import {Dot, GlassPanel, Pill, Reveal, SceneChrome, colors} from '../components/Background';

const GuardCard: React.FC<{number:string;title:string;detail:string;tone:'mint'|'cyan'|'warm';delay:number}> = ({number,title,detail,tone,delay}) => <Reveal delay={delay}><GlassPanel accent={tone} style={{height:245,padding:28}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{fontSize:23,color:colors.muted,fontWeight:900}}>{number}</div><Dot tone={tone} size={12}/></div><div style={{fontSize:34,fontWeight:900,marginTop:42,letterSpacing:-1}}>{title}</div><div style={{fontSize:22,color:colors.muted,lineHeight:1.35,marginTop:12}}>{detail}</div></GlassPanel></Reveal>;

export const ReliabilityScene: React.FC = () => {
  const frame=useCurrentFrame();
  return <SceneChrome chapter="İŞLETİLEBİLİRLİK" index={5}><div style={{position:'absolute',left:88,right:88,top:136}}><Reveal delay={4}><Pill tone="warm">PRODUCTION MINDSET</Pill></Reveal><Interactive.Div name="Güvenilirlik başlığı" style={{marginTop:20,fontSize:88,lineHeight:1,letterSpacing:-4,fontWeight:900,opacity:interpolate(frame,[9,29],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)}),translate:`0px ${interpolate(frame,[9,31],[36,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(0.16,1,0.3,1)})}px`}}>Demo değil, <span style={{color:colors.mint}}>işletilebilir süreç.</span></Interactive.Div><div style={{display:'grid',gridTemplateColumns:'repeat(4, 1fr)',gap:22,marginTop:60}}><GuardCard number="01" title="İnsan döngüde" detail="Düşük güven puanı insan incelemesine gider." tone="warm" delay={46}/><GuardCard number="02" title="Kontrollü retry" detail="API hataları en fazla 3 kez yeniden denenir." tone="mint" delay={60}/><GuardCard number="03" title="Audit log" detail="Her karar, girdi ve çıktı PostgreSQL'e yazılır." tone="cyan" delay={74}/><GuardCard number="04" title="Secret yönetimi" detail="API anahtarları environment üzerinden ayrıştırılır." tone="mint" delay={88}/></div><Reveal delay={120}><GlassPanel accent="cyan" style={{marginTop:34,padding:'28px 34px',display:'grid',gridTemplateColumns:'1.15fr 1fr 1fr',alignItems:'center',gap:30}}><div><div style={{fontSize:21,color:colors.muted,fontWeight:800,letterSpacing:1.8}}>TASARIM SONUCU</div><div style={{fontSize:38,fontWeight:900,marginTop:8}}>4 manuel adım → 1 otomasyon akışı</div></div><div style={{borderLeft:'1px solid rgba(255,255,255,0.12)',paddingLeft:34}}><div style={{fontSize:21,color:colors.muted}}>Hata yaklaşımı</div><div style={{fontSize:33,color:colors.mint,fontWeight:900,marginTop:8}}>3× retry</div></div><div style={{borderLeft:'1px solid rgba(255,255,255,0.12)',paddingLeft:34}}><div style={{fontSize:21,color:colors.muted}}>İzlenebilirlik</div><div style={{fontSize:33,color:colors.cyan,fontWeight:900,marginTop:8}}>Uçtan uca kayıt</div></div></GlassPanel></Reveal></div></SceneChrome>;
};
